### ISSUE TITLE
Ability to ignore files

### ISSUE THREAD

**Issue by sfowlr** [varunagrawal/nuke#1]
It would be very helpful if nuke could check a .nukeignore list (both a global list and one local to the folder) in order to preserve files and folders inside that aren't intended to be deleted.

**Comment by varunagrawal** [comment]
The global ignore file will be hard. I can do the local ignore easily enough, but my understanding is that the ignore file will either have to be specified or put in the directory you wish to nuke. Is that what you expect as well?

**Comment by sfowlr** [comment]
Exactly, similar to how a .gitignore file works. It should be located in the directory you wish to nuke, and contain a list of files and folders you'd like to preserve on nuke (such as a package.xml, CMakeLists template, readme, or similar) It should inherently preserve itself, too. 

The global one would be helpful as well, located in a place such as ~/.nukeignore, but that one probably isn't as important.

**Comment by varunagrawal** [comment]
Version 2 of `nuke` is out. This version supports the nukeignore feature! :smile: 
Thanks for your recommendation @sfowlr.
